#! /bin/sh

##= AUTOSTART =##
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr
bspc monitor -d 1 2 3 4 
feh --bg-scale ~/.config/bspwm/wallpaper.png
~/.config/polybar/launch.sh

##= CONFIGURES =##
bspc config top_padding             35
bspc config bottom_padding          25
bspc config left_padding            15
bspc config right_padding           15

bspc config border_width            2
bspc config window_gap              12
bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true

##= BORDER COLORS =##
bspc config normal_border_color     "#2B333B"
bspc config focused_border_color    "#EC5F67"
bspc config urgent_border_color     "#F9B578"

##= RULES =##
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Thunar desktop='^3' state=floating
