#!/bin/sh

if [[ $(xrandr | grep DP-2 | cut -d" " -f2) == "connected" ]]; then
    bspc monitor DP-2 -d 1 2 3 4 5 
    xrandr --output eDP-1 --off
else
    bspc monitor eDP-1 -d 1 2 3 4 5
fi

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
xset r rate 300 50 &
picom --experimental-backend &
dunst &
~/.config/polybar/launch.sh &
feh --bg-scale ~/.config/bspwm/wl/cherry.jpg &

bspc config border_width                2
bspc config border_radius               16
bspc config window_gap                  4
bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       false
bspc config pointer_modifier            mod4
bspc config pointer_action1             move
bspc config remove_disable_monitors     true
bspc config merge_overlapping_monitors  true

direction=("left" "right" "bottom")
default_padding=6
for each_direction in ${direction[@]}; do
    bspc config ${each_direction}_padding $default_padding
done
bspc config top_padding 45

bspc config focused_border_color   "#403D52"
bspc config normal_border_color    "#1f1d2e"

floating_apps=(
        "Imv" "Nemo" "Lxappearance"
    )
for app in ${floating_apps[@]}; do
    bspc rule -a $app state=floating
done
