#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
feh --bg-scale ~/.config/bspwm/wallpaper/wallpaper.jpg &
picom --experimental-backends &
~/.config/polybar/launch.sh &
dunst &
xrdb ~/.Xresources &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width            0
bspc config border_radius           0
bspc config window_gap              14
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true

bspc rule -a Pcmanfm state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Firefox desktop='^2'
bspc rule -a Pavucontrol state=floating sticky=on rectangle=260x315+1630+50 
bspc rule -a OBS state=floating
