[colors]
background = #343D46
foreground = #D5DEE9
primary = #EC5F67
inactive = #2D333B
warning = #F9B578

[bar/main]
monitor = 
width = 100%
height = 30
background = ${colors.background}
foreground = ${colors.foreground}

modules-left = feather arrowLeft title
modules-center = 
modules-right = bspwm arrowRight fs audio network datetime

font-0 = Hack:style=Bold:pixelsize=9;2
font-1 = "Font Awesome 5 Free:style=Solid:pixelsize=12;3"
font-2 = "Font Awesome 5 Free:style=Solid:pixelsize=51;11"

fixed-center = true
bottom = false
wm-name = bspwm
wm-restack = bspwm
override-redirect = false 

;
; TEXT/SCRIPT
;

[module/feather]
type = custom/text
content = 
content-background = ${colors.primary}
content-padding = 3

[module/arrowLeft]
type = custom/text
content = %{T3}%{T-}
content-foreground = ${colors.primary}

[module/arrowRight]
type = custom/text
content = %{T3}%{T-}
content-foreground = ${colors.primary}


;
; ALL MODULES
;

[module/title]
type = internal/xwindow

format = <label>

label = %title%
label-padding = 2
label-maxlen = 120

[module/bspwm]
type = internal/bspwm

format-padding = 2

label-focused = %index%
label-focused-foreground = ${colors.primary}

label-occupied = %index%

label-empty = %index%

label-separator = │
label-separator-foreground = ${colors.background}

[module/fs]
type = internal/fs
interval = 20
mount-0 = /

format-mounted = <label-mounted>
format-mounted-background = ${colors.primary}
format-mounted-padding = 1

label-mounted =  %free%

[module/audio]
type = internal/alsa
master-mixer = Master

format-volume = <label-volume>
format-volume-background = ${colors.primary}
format-volume-padding = 1

format-muted = <label-muted>
format-muted-background = ${colors.primary}
format-muted-foreground = ${colors.inactive}
format-muted-padding = 1

label-volume =  %percentage%%

label-muted =  --%

[module/network]
type = internal/network
interface = enp0s3
interface-type = wired

format-connected = <label-connected>
format-connected-background = ${colors.primary} 
format-connected-padding = 1

format-disconnected = <label-disconnected>
format-disconnected-foregorund = #{colors.inactive}
format-disconnected-padding = 1

label-connected =  OK

label-disconnected =  NO

[module/datetime]
type = internal/date

format = <label>
format-background = ${colors.primary}
format-padding = 1

label = " %time%%date%"

time = %R %p
date-alt = %D
